modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="ragemod"
version="1.1_21w45a"
displayName="RageMod (forge)"
credits="Made by: RageTeam: CrashGyuluka"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ragemod-by-rageteam"
logoFile="logo.png"
authors="CrashGyuluka, Lyof"
description='''
I hope you will enjoy this mod! Main dev: CrashGyuluka, some textures: Lyof
'''

[[dependencies.ragemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




