modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"

[[mods]]
modId="ragemod"
version="1.1 Pre-release2"
displayName="RageMod"
credits="Made by CrashGyuluka"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ragemod-by-rageteam"
logoFile="logo.png"
authors="CrashGyuluka, Lyof"
description='''
I hope you will enjoy this mod! Main dev: CrashGyuluka, some textures: Lyof
'''

[[dependencies.ragemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




